name: Docs
on:
  push:
    paths:
    - 'docs/**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  builddocs:
    name: Build Doc Frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Build Docs
      uses: caos/site@master
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: export
        path: __sapper__/export
        
  deploydocs:
    name: Deploy
    needs: builddocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: export
          path: __sapper__/export
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: __sapper__/export
          CLEAN: true
